import favicon from "@/app/favicon.svg";

export default function Head() {
  return (
    <>
      <title>My Next.js App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={favicon} />
    </>
  );
}
